### ISSUE TITLE
Alias on `find` output errors

### ISSUE THREAD

**Issue by pinage404** [b4b4r07/enhancd#104]
I'm using `enhancd` on `Fish` (using `omf`) on `NixOS`

i have this alias in my Fish config

```fish
alias find="fd"
```

Because i would like to use [`fd`](https://github.com/sharkdp/fd) when i looking for something

**What did you expect to happen?**
Having an alias on `find` and having `enhancd` that works

**What actually happened?**

On this line, `find` is used with an option that `fd` doesn't know

https://github.com/b4b4r07/enhancd/blob/9ac688768442bc6115f84f15518b72935b63bb16/functions/_enhancd_filepath_walk.fish#L6

**Output**
```text 
cd Project
no entry
error: Found argument '-m' which wasn't expected, or isn't valid in this context

USAGE:
    fd [FLAGS/OPTIONS] [<pattern>] [<path>...]

For more information try --help
```

---

How can i solve this issue ?

Thanks for any help

**Comment by Croissong** [comment]
Hi, I'm facing the same issue.
Although I've had the alias for a while and am only getting the enhancd error since recently.
I can't pinpoint the commit that caused this regression however.

I suppose it makes sense to make the find commands configurable?

**Comment by pinage404** [comment]
the problem is still present

**Comment by Croissong** [comment]
the problem is still present

**Comment by Gazorby** [comment]
The real problem here is that `find` uses `-` for both short and long options (instead of using `--` for long options), despite the fact that `maxdepth` and `type` options exists for both `find` and `fd` commands.

A quick fix for fish is to use `command find` instead of `find`, which will bypass the alias. strangely, i'm not able to reproduce this issue with zsh.

As @Croissong pointed out, it would make sense to make this configurable, through a `ENHANCD_FIND_COMMAND` env variable for example, but it would require a little pre parsing to add an extra `-` for `fd`

**Comment by b4b4r07** [comment]
hi, thank you for opening issue and sorry for late reply. I’ll take a look this later

**Comment by b4b4r07** [comment]
Hi, I'm fixing it with 7a8c849. Feel free to re-open this if you still have opinion! Thanks

**Comment by pinage404** [comment]
It works great, thanks :tada:
