### ISSUE TITLE
possible to list hidden directories?

### ISSUE THREAD

**Issue by arkinzoodsma** [b4b4r07/enhancd#78]
Hello, 

I love your work however I had a question is it possible to also list hidden directories?
And does it only work from the home directory or did I configure something wrong?

Thanks!

**Comment by b4b4r07** [comment]
>I had a question is it possible to also list hidden directories?

Is it a directory name that begins with "."?

**Comment by dylanjm** [comment]
Yes, this user was probably experiencing the same problem I'm having

When I type from my home folder:

```bash
$ cd <TAB>
```

![image](https://user-images.githubusercontent.com/15963026/70472218-fd42a100-1a8b-11ea-939a-5c91876d65fc.png)

I only get a list of directories that are not hidden. Meaning they do not start with a `.`

I think the expected behavior would work similarly to using autocomplete in zsh such that all folders are available to `cd` into. 

Here are some relevant `env` vars:

```bash
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git"'

export ENHANCD_DIR="$XDG_CACHE_HOME/zsh/enhancd"
export ENHANCD_FILTER=fzf:fzy:peco
export ENHANCD_COMPLETION_BEHAVIOR=list
export ENHANCD_DISABLE_HOME=1
```

**Comment by s1341** [comment]
it seems that enhancd does not respect FZF_DEFAULT_COMMAND...

Can we add this? If you point me in the right direction, I can make the changes and open a PR.

**Comment by creepinson** [comment]
I'd like this as well.
